### ISSUE TITLE
Cannot Install - Hash Mismatch

### ISSUE THREAD

**Issue by allluke** [YunoHost-Apps/streams_ynh#21]
### Describe the bug

There is a hash mismatch while trying to install on yunohost.

### Context

- Hardware: *VPS bought online 
- YunoHost version: 11.2.5 (stable)
- I have access to my server: *Through SSH and through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: stable
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*: N/A

### Steps to reproduce

Try and install from yunohost gui

### Expected behavior

Install completes, however it fails with hash mismatch.

### Logs

https://paste.yunohost.org/raw/edobufuzup

**Comment by dragondaddy** [comment]
Just saw that, I'm on it

**Comment by allluke** [comment]
sweet thanks!

**Comment by dragondaddy** [comment]
Finalizing some testing and we should be good. Just a matter of minutes.

**Comment by allluke** [comment]
Great thank you!

**Comment by dragondaddy** [comment]
Just a matter of minutes to push the change but apparently it takes a little more time before the app is actually available through the YunoHost admin interface... We'll have to wait a little.

Or if you're really impatient, you could try an install from a custom repository in the YunoHost app installation interface, using the following: https://github.com/YunoHost-Apps/streams_ynh/tree/8985f0af2e713f8fc514dcf4b42208d1329f2403

**Comment by dragondaddy** [comment]
Should be fixed with version 23.11.05~ynh3 of the package. Not yet available through the YunoHost admin interface, so let's wait a bit (or do things manually for those who just can't wait)

**Comment by dragondaddy** [comment]
It works! @allluke if you can confirm that it's also OK on your side, I'll close the issue then

**Comment by allluke** [comment]
Yes I can confirm it's working on my end thanks. Just installed and good to go.

**Comment by dragondaddy** [comment]
Solved with https://github.com/YunoHost-Apps/streams_ynh/commit/8985f0af2e713f8fc514dcf4b42208d1329f2403
